In [19]:
import numpy as np 
import pandas as pd 



In [20]:
df = pd.read_csv('CAR DETAILS FROM CAR DEKHO.csv',
                 usecols=['fuel','name','seller_type','transmission','owner'])
df.head()
df.sample(5)




,name,fuel,seller_type,transmission,owner
3573,Maruti Wagon R LXI Minor,Petrol,Individual,Manual,Second Owner
418,Hyundai Santro Era,Petrol,Individual,Manual,First Owner
2975,Maruti Ritz VDi,Diesel,Individual,Manual,Second Owner
2688,Renault Duster 85PS Diesel RxL,Diesel,Individual,Manual,Second Owner
433,Ford Figo Diesel Titanium,Diesel,Individual,Manual,Second Owner


In [21]:
# Using python 

# df['transmission'] = df['transmission'].map({'Manual':0,'Automatic':1})
# df['seller_type'] = df['seller_type'].map({'Individual':0,'Dealer':1,'Trustmark Dealer':2})
# df.sample(9)

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('fuel',axis=1),df['fuel'], test_size=0.2, random_state=42)


In [23]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder
le = LabelEncoder()
label_y_train = le.fit_transform(y_train)
label_y_test = le.transform(y_test)
# label_y_train = pd.DataFrame(data=label_y_train, columns=y_train.columns)
label_y_train

array([1, 1, 4, ..., 1, 1, 4], shape=(3472,))

In [28]:
oe = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
oe_X_train = oe.fit_transform(X_train)
oe_X_test = oe.transform(X_test)
oe_X_train

array([[606.,   1.,   1.,   0.],
       [863.,   1.,   1.,   0.],
       [698.,   1.,   1.,   2.],
       ...,
       [759.,   0.,   1.,   0.],
       [782.,   1.,   1.,   0.],
       [411.,   1.,   1.,   0.]], shape=(3472, 4))

In [26]:
oe_X_train


array([[606.,   1.,   1.,   0.],
       [863.,   1.,   1.,   0.],
       [698.,   1.,   1.,   2.],
       ...,
       [759.,   0.,   1.,   0.],
       [782.,   1.,   1.,   0.],
       [411.,   1.,   1.,   0.]], shape=(3472, 4))